version: "3"  # optional since v1.27.0
services:
  web_aplicatie3:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3002:3000"
    volumes: 
      - ./aplicatie3:/opt/app
      - gem_cache_aplicatie3:/gems
    env_file: 
      - .env/development/database_aplicatie3
      - .env/development/web_aplicatie3
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_aplicatie3
  webpack_dev_server_aplicatie3:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3037:3037"
    volumes: 
      - ./aplicatie3:/opt/app
      - gem_cache_aplicatie3:/gems
    env_file: 
      - .env/development/database_aplicatie3
      - .env/development/web_aplicatie3
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  database_aplicatie3:
    image: postgres
    env_file: 
      - .env/development/database_aplicatie3
    volumes: 
      - db_data_aplicatie3:/var/lib/postgresql/data
volumes: 
  db_data_aplicatie3:
  gem_cache_aplicatie3: